# Generated by Django 4.2.3 on 2023-08-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='joined_date',
            new_name='dateofbirth',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone',
        ),
        migrations.AddField(
            model_name='member',
            name='emailid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
